### ISSUE TITLE
yarn test errors

### ISSUE THREAD

**Issue by jakubvul** [okta/okta-developer-docs#56]
Many errors, including:

```
50) quickstart page content spec should load the .NET/ASP 4 content when I click .NET/ASP 4
  ✓ sidebar navigation spec has links in side navigation: 106ms
    sidebar navigation spec contains Authentication Reference sub-links on reference side navigation: Error during Promise resolution:  No element found using locator: By(link text, Sign in Your Users)
[...]
    sidebar navigation spec contains API Reference sub-links on reference side navigation: Error during Promise resolution:  No element found using locator: By(link text, Manage Okta Resources)
```

```
1) page layout and browser size spec
       shows the main navigation with desktop browser sizes:

      expects Desktop Nav to be displayed
      + expected - actual

      -false
      +true

      at util.itHelper (tests/selenium/spec/page-layout-browser-size-spec.js:21:95)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

  2) quickstarts page default selections spec
       selects okta-sign-in-page + nodejs + express if nothing is specified:

      AssertionError: expected [ '', '', '' ] to be a superset of [ Array(3) ]
      + expected - actual

       [
      -  ""
      -  ""
      -  ""
      +  "Okta Sign-In Page"
      +  "Node JS"
      +  "Express.js"
       ]
```

and so on.

**Comment by bretterer** [comment]
can you try, `yarn dev` and then `yarn test-only` @jakubvul

**Comment by jakubvul** [comment]
> can you try, `yarn dev` and then `yarn test-only` @jakubvul

Same errors, as far as I can tell.

**Comment by bretterer** [comment]
so, I have been running into this to the last 24 hours @wje600   It seems that running `yarn stop` before running `yarn test-only` will fix this issue?

**Comment by wayneearl-okta** [comment]
i think the latest tweaks to the tests have resolved the issue(s) above.

**Comment by bretterer** [comment]
@jakubvul if this is still an issue, please re-open this issue
